// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGrqHvAUhFnsLFav0fiZogzbS1u2XWwvs',
    appId: '1:932808679937:web:2808288fd46bb493a3d600',
    messagingSenderId: '932808679937',
    projectId: 'tssperformance-1f5ac',
    authDomain: 'tssperformance-1f5ac.firebaseapp.com',
    storageBucket: 'tssperformance-1f5ac.appspot.com',
    measurementId: 'G-2DHLSX3Z6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvg7W2lnK9CN68p3FIKrXFVpqT0kLvxuY',
    appId: '1:932808679937:android:a87b425cea8e04e1a3d600',
    messagingSenderId: '932808679937',
    projectId: 'tssperformance-1f5ac',
    storageBucket: 'tssperformance-1f5ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9BAzqvhKZwXZcCHIoLCOEofYlw61b4A',
    appId: '1:932808679937:ios:b8b26840fc34065da3d600',
    messagingSenderId: '932808679937',
    projectId: 'tssperformance-1f5ac',
    storageBucket: 'tssperformance-1f5ac.appspot.com',
    iosBundleId: 'mobile.tssperformance.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH9BAzqvhKZwXZcCHIoLCOEofYlw61b4A',
    appId: '1:932808679937:ios:6c8cce8029e0d0d3a3d600',
    messagingSenderId: '932808679937',
    projectId: 'tssperformance-1f5ac',
    storageBucket: 'tssperformance-1f5ac.appspot.com',
    iosBundleId: 'com.example.tsscourses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGrqHvAUhFnsLFav0fiZogzbS1u2XWwvs',
    appId: '1:932808679937:web:cdddb0a12e826969a3d600',
    messagingSenderId: '932808679937',
    projectId: 'tssperformance-1f5ac',
    authDomain: 'tssperformance-1f5ac.firebaseapp.com',
    storageBucket: 'tssperformance-1f5ac.appspot.com',
    measurementId: 'G-CXMKPH5XFE',
  );
}
